### ISSUE TITLE
App wont start.. 

### ISSUE THREAD

**Issue by nerdtechse** [balmli/com.lametric.time#4]
Tried to install the app from cli but it went to paused directly so i tried homey app run instead and i then got this in logg.. 

Warning: Trying to access `Homey.env.CLIENT_ID` but the environment variable has not been set!
Warning: Trying to access `Homey.env.CLIENT_SECRET` but the environment variable has not been set!
Unable to initialize app OAuth2Error: Invalid Client ID
    at LametricTimeApp.setOAuth2Config (/node_modules/homey-oauth2app/lib/OAuth2App.js:75:13)
    at LametricTimeApp.onOAuth2Init (/app.js:11:14)
    at LametricTimeApp.onInit (/node_modules/homey-oauth2app/lib/OAuth2App.js:21:17)
    at SDK._initApp (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:284:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDK.createClient (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:172:5)

--- INFO: com.lametric.time has been killed ---

**Comment by balmli** [comment]
Yes, the env.json file is missing, with CLIENT_ID and CLIENT_SECRET.

You can install the app from the Homey Community Store:
https://store.homey.community/app/com.lametric.time

That should work :-)
